VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub clearAllLinks()
    Call Sheet1.clearLinks
    Call Sheet2.clearLinks
    Call Sheet3.clearLinks
    Call Sheet4.clearLinks
    Call Sheet5.clearLinks
    Call Sheet6.clearLinks
    Call Sheet7.clearLinks
    Call Sheet8.clearLinks
    Call Sheet9.clearLinks
    Call Sheet10.clearLinks
    Call Sheet11.clearLinks
    Call Sheet12.clearLinks
    Call Sheet13.clearLinks
    Call Sheet14.clearLinks
    Call Sheet15.clearLinks
    Call Sheet17.clearLinks
    Call Sheet18.clearLinks
End Sub

